import { useMutation } from "@tanstack/react-query";
import { Download, FlaskConical, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { challengeCheck, type ChallengeCandidate, type ChallengeCheckRequest, type ChallengeVariant } from "../api/workflows";
import type { SuiteVersion } from "../types";

export function ChallengeLab({ version }: { version: SuiteVersion }) {
  const [caseKey, setCaseKey] = useState(version.cases[0]?.stable_key ?? "");
  const [variants, setVariants] = useState<ChallengeVariant[]>([]);
  const [candidates, setCandidates] = useState<ChallengeCandidate[]>([{ name: "典型错解 1", sql: "", expected: "incorrect" }]);
  const [submitted, setSubmitted] = useState<ChallengeCheckRequest | null>(null);
  const check = useMutation({ mutationFn: (payload: ChallengeCheckRequest) => challengeCheck(version.id, payload) });
  const selectedCase = version.cases.find((item) => item.stable_key === caseKey);
  const payload: ChallengeCheckRequest = { case_key: caseKey, variants: [{ name: "原始数据", seed_sql: version.seed_sql }, ...variants], candidates };
  const names = [...payload.variants.map((item) => item.name.trim()), ...candidates.map((item) => item.name.trim())];
  const valid = Boolean(caseKey && candidates.length && candidates.every((item) => item.sql.trim() && item.name.trim()) && variants.every((item) => item.seed_sql.trim() && item.name.trim()) && new Set(names).size === names.length);
  const changed = submitted && JSON.stringify(submitted) !== JSON.stringify(payload);
  const download = () => {
    if (!check.data || !submitted) return;
    const blob = new Blob([JSON.stringify({ schema_version: "challenge-review-v1", source_version_id: version.id, source_content_hash: version.content_hash, input: submitted, result: check.data }, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = `challenge-${version.id}-${submitted.case_key}.json`; anchor.click(); URL.revokeObjectURL(url);
  };
  return <section className="challenge-lab" aria-labelledby="challenge-title"><p className="eyebrow">题目也要接受考试</p><h2 id="challenge-title">这道题，能揪出错误答案吗？</h2><p>正解能通过，还不够。把典型错解放到原始数据和固定数据变体里执行，检查它是否只是碰巧答对。不调用模型，也不修改已锁定题库。</p>
    <label>选择要检查的题目<select value={caseKey} onChange={(event) => setCaseKey(event.target.value)}>{version.cases.map((item) => <option key={item.stable_key} value={item.stable_key}>{item.title}</option>)}</select></label>{selectedCase && <p className="notice">{selectedCase.question}</p>}
    <div className="challenge-fields"><section><h3>数据变体</h3><p><small>原始 Seed 自动参与。额外变体是完整的 Seed SQL，不是增量补丁。可以修改重复记录、边界日期、空值或并列值。</small></p>{variants.map((variant, index) => <div className="challenge-item" key={index}><header><b>变体 {index + 1}</b><button className="icon-only" aria-label={`删除变体 ${index + 1}`} onClick={() => setVariants((values) => values.filter((_, i) => i !== index))}><Trash2/></button></header><label>名称<input value={variant.name} maxLength={80} onChange={(event) => setVariants((values) => values.map((item, i) => i === index ? { ...item, name: event.target.value } : item))}/></label><label>完整 Seed SQL<textarea spellCheck={false} value={variant.seed_sql} onChange={(event) => setVariants((values) => values.map((item, i) => i === index ? { ...item, seed_sql: event.target.value } : item))}/></label></div>)}<button className="button" disabled={variants.length >= 9} onClick={() => setVariants((values) => [...values, { name: `数据变体 ${values.length + 1}`, seed_sql: version.seed_sql }])}><Plus/>从原始数据添加变体</button></section>
    <section><h3>待检验的 SQL</h3><p><small>“典型错解”必须至少被一组数据区分。语法错误或执行失败不算题目有辨错能力。</small></p>{candidates.map((candidate, index) => <div className="challenge-item" key={index}><header><b>候选答案 {index + 1}</b><button className="icon-only" aria-label={`删除候选答案 ${index + 1}`} disabled={candidates.length === 1} onClick={() => setCandidates((values) => values.filter((_, i) => i !== index))}><Trash2/></button></header><label>名称<input value={candidate.name} maxLength={80} onChange={(event) => setCandidates((values) => values.map((item, i) => i === index ? { ...item, name: event.target.value } : item))}/></label><label>我们预期它是<select value={candidate.expected} onChange={(event) => setCandidates((values) => values.map((item, i) => i === index ? { ...item, expected: event.target.value as ChallengeCandidate["expected"] } : item))}><option value="incorrect">典型错解 · 应被数据区分</option><option value="correct">等价正解 · 应在各组通过</option></select></label><label>只读 SQL<textarea value={candidate.sql} spellCheck={false} placeholder="输入需要检查的只读查询" onChange={(event) => setCandidates((values) => values.map((item, i) => i === index ? { ...item, sql: event.target.value } : item))}/></label></div>)}<button className="button" disabled={candidates.length >= 20} onClick={() => setCandidates((values) => [...values, { name: `典型错解 ${values.length + 1}`, sql: "", expected: "incorrect" }])}><Plus/>添加候选答案</button></section></div>
    <div className="challenge-controls"><button className="button primary" disabled={!valid || check.isPending} onClick={() => { setSubmitted(payload); check.mutate(payload); }}><FlaskConical/>{check.isPending ? "正在本地执行与比较…" : "运行辨错自检"}</button><small>{payload.variants.length} 组固定数据 · {candidates.length} 条候选 SQL · 临时隔离执行</small></div><p><small>使用此版本已保存的源文件。草稿若有未保存编辑，请先保存；实验结果不等于模型得分，也不会替你发布新版本。</small></p>
    {check.error && <p className="notice error" role="alert">{(check.error as Error).message}</p>}
    {check.data && <div className="challenge-result" aria-live="polite"><div className="section-title"><h3>{check.data.summary.passed ? "这批候选符合预期" : "发现还需检查的边界"}</h3><button className="button" onClick={download}><Download/>导出实验记录</button></div>{changed && <p className="notice">输入已修改。以下仍是上一次执行的结果，请重新自检。</p>}<p><small>符合预期 {check.data.summary.passed_candidates} / {check.data.summary.candidate_count} 条。结果仅覆盖本次选定的数据与候选 SQL。</small></p><table><thead><tr><th>数据</th><th>候选</th><th>实际结果</th><th>证据</th></tr></thead><tbody>{check.data.variants.flatMap((variant) => variant.candidates.map((candidate) => <tr key={`${variant.name}-${candidate.name}`}><td>{variant.name}<br/><small>参考答案：{variant.baseline.result_correct ? "通过" : "未通过"}</small></td><td>{candidate.name}<br/><small>预期{candidate.expected === "correct" ? "正确" : "错误"}</small></td><td>{candidate.status === "execution_error" ? "执行失败 · 不算区分" : candidate.distinguished ? "错解已被区分" : candidate.result_correct ? "与金标一致" : "结果不同"}</td><td>{candidate.error_message && <p>{candidate.error_message}</p>}{candidate.diff && <details><summary>查看真实结果差异</summary><pre>{JSON.stringify(candidate.diff, null, 2)}</pre></details>}</td></tr>))}</tbody></table></div>}
  </section>;
}
