"""initial schema

Revision ID: 7584fd247605
Revises:
Create Date: 2026-08-29 22:55:53.291784
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7584fd247605'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('adapter_kind', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('response_mode', sa.String(length=24), nullable=False),
    sa.Column('api_key_ref', sa.String(length=300), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=24), nullable=False),
    sa.Column('health_details_json', sa.JSON(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suite_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dialect', sa.String(length=24), nullable=False),
    sa.Column('schema_sql', sa.Text(), nullable=False),
    sa.Column('seed_sql', sa.Text(), nullable=False),
    sa.Column('semantic_layer_json', sa.JSON(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('structure_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['benchmark_suites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('suite_id', 'version')
    )
    op.create_table('benchmark_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_version_id', sa.Integer(), nullable=False),
    sa.Column('stable_key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('radar_dimension', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('reference_sql', sa.Text(), nullable=False),
    sa.Column('required_ast_json', sa.JSON(), nullable=False),
    sa.Column('comparison_json', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['suite_version_id'], ['suite_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_version_id', 'stable_key')
    )
    op.create_table('comparison_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.Column('suite_version_id', sa.Integer(), nullable=False),
    sa.Column('suite_content_hash', sa.String(length=64), nullable=False),
    sa.Column('selected_case_keys_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_event_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_run_id'], ['comparison_runs.id'], ),
    sa.ForeignKeyConstraint(['suite_version_id'], ['suite_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_run_id', sa.Integer(), nullable=False),
    sa.Column('model_profile_id', sa.Integer(), nullable=False),
    sa.Column('selection_order', sa.Integer(), nullable=False),
    sa.Column('adapter_kind_snapshot', sa.String(length=32), nullable=False),
    sa.Column('base_url_snapshot', sa.String(length=500), nullable=True),
    sa.Column('response_mode_snapshot', sa.String(length=24), nullable=False),
    sa.Column('requested_model_id', sa.String(length=200), nullable=False),
    sa.Column('resolved_model_id', sa.String(length=200), nullable=True),
    sa.Column('parameters_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('api_key_ref_snapshot', sa.String(length=300), nullable=True),
    sa.Column('cli_version_snapshot', sa.String(length=120), nullable=True),
    sa.Column('isolation_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('official_score', sa.Float(), nullable=True),
    sa.Column('conclusion_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['comparison_run_id'], ['comparison_runs.id'], ),
    sa.ForeignKeyConstraint(['model_profile_id'], ['model_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_case_id', sa.Integer(), nullable=False),
    sa.Column('stable_case_key_snapshot', sa.String(length=120), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt_snapshot', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('visible_summary', sa.Text(), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('formatted_sql', sa.Text(), nullable=True),
    sa.Column('execution_ms', sa.Float(), nullable=True),
    sa.Column('token_usage_json', sa.JSON(), nullable=True),
    sa.Column('expected_digest', sa.String(length=64), nullable=True),
    sa.Column('actual_digest', sa.String(length=64), nullable=True),
    sa.Column('result_preview_json', sa.JSON(), nullable=True),
    sa.Column('score_breakdown_json', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_case_id'], ['benchmark_cases.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'benchmark_case_id', 'attempt')
    )
    op.create_table('run_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_run_id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('case_run_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_run_id'], ['case_runs.id'], ),
    sa.ForeignKeyConstraint(['comparison_run_id'], ['comparison_runs.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_run_id', 'seq')
    )
    op.create_index('ix_run_events_run_seq', 'run_events', ['comparison_run_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_events_run_seq', table_name='run_events')
    op.drop_table('run_events')
    op.drop_table('case_runs')
    op.drop_table('model_runs')
    op.drop_table('comparison_runs')
    op.drop_table('benchmark_cases')
    op.drop_table('suite_versions')
    op.drop_table('model_profiles')
    op.drop_table('benchmark_suites')
    # ### end Alembic commands ###
